### PR TITLE
Fixes #3: Modifying Regex

### LINKED ISSUE #3: Modifying Regex and Webscrapping YouTube (Difficulty - Medium)
The downloader uses regex to check whether the url entered is one that is valid. The regex used currently is not strict in certain cases . In other words , there are ways invalid urls may pass through the regex. 
1 . Modify the regex and check that no invalid urls can get through.
Files to be modified - wizzyDownload.html
Tag - JavaScript

Difficulty - Easy
The code in wizzyDownload also uses ajax to scrape html from the entered valid url and extract the name of the song from the page. But there are issues related to ajax scraping. I need a better implementation of the code using a scrapper to scrape the name of the song from the youtube url entered.
2. Modify the incode implementation of youtube webscrapping using any flexible scrapper and integrate it with the code so that finally when the user clicks the Check URL button the scrapper successfully scrapes the name of the song .
Integrate django with the scraper.

Files to be modified - wizzyDownload.html , you can create any related file for the scraper if you are using python scrapers/modules.

Difficulty - Medium

### PR DESCRIPTION
**Pull request by the-codingninja**
Fixes Regex Part of the Issue.

Check this [link](http://www.rubular.com/r/Xs3jwq4CUo) for checking regex.

@EmberCS15

### CODE REVIEW

**Review by sachincool — APPROVED** [review]
LGMT  
Cheers!
@0x48piraj  What do you say ?

**Review by 0x48piraj — APPROVED** [review]
LGTM! , CHEEERS!! :tada: 
Doing good! Keep contributing :100:

**Comment by EmberCS15** [comment]
Your regex is ok but the javaScript syntax for regex is wrong. Correct the syntax. Run the Code and the application. Try out a few Strings and see if it should be passed by the regex. Also if possible try out the following - 
1) From any string, I need only the till the following portion v=w0EF3AxJwLU in string
https://www.youtube.com/watch?v=w0EF3AxJwLU&list=RDMMw0EF3AxJwLU
Similarly for any string, if it is valid extract on the part till https://www.youtube.com/watch?v=w0EF3AxJwLU and feed it to the downloader.
2)To modify the regex enclose regex between '/' eg. /regex/.

**Comment by ms10398** [comment]
I am not able to run the project locally. Django is not able to install I checked the error online but got no solution and got to know as with latest python release it doesnt works.
Can you help me on this?

**Comment by EmberCS15** [comment]
Download and install previous python version(3.5). I am currently running
python 3.6 and Django is working properly on my lappy. Use pip to install
Django.

**Comment by the-codingninja** [comment]
I have made the given changes @EmberCS15 
Please review

**Comment by the-codingninja** [comment]
Yeah i made it to work out @EmberCS15 
And checked and corrected the regex

**Comment by EmberCS15** [comment]
Try out the other things I suggested and make PR.

**Comment by the-codingninja** [comment]
By other things you mean which part @EmberCS15 ?

**Comment by the-codingninja** [comment]
Thanks will try out other things with the project

**Comment by EmberCS15** [comment]
I mentioned two points above. Try your hand at the first point. Also, you can look into the other issues present. Cheers.

**Pull request merged**
