### PR TITLE
Added Installation Guide to README

### PR DESCRIPTION
**Pull request by harsh-jindal**
Updated Readme #5

I have made the changes.

### CODE REVIEW

**Comment by EmberCS15** [comment]
Can you add steps for the user guiding him/her on how to - 
1) clone the repo from GitHub(involves installation of git on terminal/git bash in windows) and other steps.

2) How to start up with the project i.e navigating to the project directory and typing in relevant Django commands to get the server up and running.

3) Also, lay down guidelines for the user on how to download a video and view previously downloaded videos in the profile section. 

Overall good. Try your hand on the intermediate issues (Regex would be a nice start).

**Comment by harsh-jindal** [comment]
Okay I'll try.

**Comment by harsh-jindal** [comment]
On trying to run the project by using the command "python manage.py runserver", I get an error message of [ Could not import settings 'YouTubeDownloader.settings' (Is it on sys.path?): No module named YouTubeDownloader.settings ]. I have no idea on how to resolve this error. Could u help me out here?

**Comment by EmberCS15** [comment]
It seems to be working fine on my PC. Thus the error must be on your local system. Have you modified/renamed the settings file??
Look up on the following URLs to check for possible solutions - 
https://stackoverflow.com/questions/12987648/importerror-could-not-import-settings
https://www.pythonanywhere.com/forums/topic/1109/

You create a pull request with all the new changes you made.

**Comment by harsh-jindal** [comment]
That error is gone but I get new error regarding [ ImportError: No module named apps ].
I looked on the internet for solution but couldn't figure it out.
Shall I create pull request without laying down the guidelines for the user on how to download a video and view previously downloaded videos in the profile section ?

**Comment by EmberCS15** [comment]
Give me a walkthrough of your directory structure.

**Comment by harsh-jindal** [comment]
My directory looks like:
/Users/harsh/Wizzy-Downloader/:
manage.py
YouTubeDownloader
downloader
README.md
LICENSE.txt
db.sqlite3

And my Django(named virtualenvfolder) folder:
/Users/harsh/Desktop/virtualenvfolder/mydjango
   bin
   lib
   include
   pip-selfcheck.json
   manage.py
   YouTubeDownloader
   downloader

I copied manage.py , YouTubeDownloader, downloader into mydjango folder thinking that might be causing the problem.

**Comment by EmberCS15** [comment]
Try without using virtualenv. Use python3 and Django 1.11.0 . Run directly
from the project folder using python manage.py runserver. If required clone
the project again. Meanwhile leave the downloading part out and update your
PR.

**Comment by harsh-jindal** [comment]
@EmberCS15 I have updated the README (leaving the downloading part).

**Pull request merged**
